name: Generate Powered-By
on: 
  push:

jobs:
  generate-powered-by:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install node 
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org

    - name: Install license-report and jq
      run: |
        sudo apt-get update -y && sudo apt-get install -y jq
        sudo npm install -g license-report
    - name: Install project dependencies
      run: |
        npm ci
    - name: Make script executable
      run: chmod +x generate_powered-by.sh
    - name: Generate Powered-By for 'sc-deployer'
      run: |
        cd packages/sc-deployer && npm i && ./../../generate_powered-by.sh && cd ../../
    - name: Generate Powered-By for 'sc-project-initializer'
      run: |
        cd packages/sc-project-initializer && npm i && ./../../generate_powered-by.sh && cd ../../
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        token: ${{ secrets.MASSABOTCLASSIC }}
        commit_message: "Generate powered-by"
        file_pattern: "**/powered-by.md"
        commit_user_email: info@massa.net
        commit_user_name: massabot
        commit_author: massabot <info@massa.net>
        push_options: '--force'